### PR TITLE
Extended class "class"

### PR DESCRIPTION
**Pull request by misterquestions**
Brings more functionality like inheritance, constructors and destructors aswell.

### CODE REVIEW

**Comment by MegadreamsBE** [comment]
How much extra overhead does this bring? The old system had a very basic inheritance that should mostly be enough and doesn't slow execution down too badly.

**Comment by misterquestions** [comment]
It shouldn't give a significant performance impact unless you make maybe 50 classes inherited with strong constructors or destructors. (Telling it cause of the class tree generation)

**Comment by MegadreamsBE** [comment]
Any specific numbers you can give me? MTA on its own already doesn't have the greatest performance and despite this just being a gameboy emulator we do need to squeeze out as much performance as we can. If the numbers look good I'll merge this after a quick test.

**Comment by MegadreamsBE** [comment]
Due to inactivity and the fact that you removed your fork I'll consider this PR abandoned.

**Pull request closed without merging**
